name: mais_acai
description: Aplicativo da loja +Açaí

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  provider: ^4.1.3
  flutter_slidable: ^0.5.4
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
  - family: Manrope
    fonts:
    - asset: fonts/Manrope-Regular.otf
      weight: 400
    - asset: fonts/Manrope-SemiBold.otf
      weight: 600
    - asset: fonts/Manrope-Bold.otf
      weight: 700

  assets:
    - assets/